[package]
name = "ignore_crate_experiments"
version = "0.1.0"
authors = ["andy.boot <bootandy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ignore="0.4.12"
crossbeam-channel = "0.4.2"
walkdir="2.3"